name: Deploy

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
   
    steps:
      - name: Imprime variable
        run: echo "${{ secrets.TOKEN_SECRET }}"
        #run: echo "Valor de la variable: ${{ secrets.TOKEN_SECRET }}"

     # - name: Run first job
     #   run: echo "This is the first job"
  