name: Deploy

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
   
#    services:
#      redis:
#        image: redis
#        ports:
#          - 6379:6379
     
    steps:
#      - name: Instalar Redis CLI
#        run: sudo apt-get update -y && sudo apt-get install redis-tools -y    

#      - name: Testear Redis
#        run: redis-cli -h localhost -p 6379 ping
             
#      - name: Imprime variable
#        run: echo "${{ secrets.TOKEN_SECRET }}"
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'
 
      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test  
  
      - name: Construir pagina
        run: npm run build

      - name: Cargar Artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/


  deploy:
    runs-on: ubuntu-latest
    needs: Build
  
    permissions:
      pages: write
      id-token: write
      

    environment:
      name: github-pages
      url: $ {{ steps.Despliega-Paginas.outputs.page_url }}


    steps:
      - name: deploy
        id: Despliega-Paginas
        uses: actions/deploy-pages@v4
       