name: Deploy

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
   
#    services:
#      redis:
#        image: redis
#        ports:
#          - 6379:6379
     
    steps:
#      - name: Instalar Redis CLI
#        run: sudo apt-get update -y && sudo apt-get install redis-tools -y    

#      - name: Testear Redis
#        run: redis-cli -h localhost -p 6379 ping
             
      - name: Imprime variable
        run: echo "${{ secrets.TOKEN_SECRET }}"
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'
 
      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test  
  
      - name: Construir pagina
        run: npm run build

  deploy:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: Build
    
    steps:
      - name: Desplegar
        run: echo "Deploy........."
