name: Deploy

on: push

jobs:
  Build:
    runs-on: ${{ matrix.os }}
   
#    services:
#      redis:
#        image: redis
#        ports:
#          - 6379:6379
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18, 20]


    steps:
#      - name: Instalar Redis CLI
#        run: sudo apt-get update -y && sudo apt-get install redis-tools -y    

#      - name: Testear Redis
#        run: redis-cli -h localhost -p 6379 ping
             
#      - name: Imprime variable
#        run: echo "${{ secrets.TOKEN_SECRET }}"
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
 
      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test  
  
      - name: Construir pagina
        run: npm run build

      - name: Cargar Artefacto
        if: ${{ matrix.os == 'ubuntu-latest' }} && matrix.node-version == '18'
        # Solo se sube el artefacto si es Ubuntu y Node 18
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/


  deploy:
    runs-on: ubuntu-latest
    needs: Build
  
    permissions:
      pages: write
      id-token: write
      

    environment:
      name: github-pages
      url: ${{ steps.Despliega-Paginas.outputs.page_url }}


    steps:
      - name: deploy
        id: Despliega-Paginas
        uses: actions/deploy-pages@v4
       
  notificar:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ always() }}
    
    steps:
      - name: notificar al slack
        uses: 8398a7/actions-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK }}
     
        with:
          status: ${{ job.status }}
          fields: repository,commit,author,job,took
            