name: Deploy

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
   
    steps:
      - name: Imprime variable
        run: echo "${{ secrets.TOKEN_SECRET }}"
        

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          #cache: 'npm'
  